[project]
name = "multiscat-new"
version = "0.1.0"
description = "Multiscat Fortran project plotting dependencies"
requires-python = ">=3.14"
dependencies = [
  "numpy",
  "pandas",
  "seaborn",
  "matplotlib",
  "multiscat",
  "numpy>=2.0.0,<3.0.0",
    "scipy>=1.14.0,<2.0.0",
    ]

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "refactor",
]

[tool.uv.sources]
multiscat = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.15.6",
]
