[project]
name = "multiscat-new"
version = "0.1.0"
description = "Multiscat Fortran project plotting dependencies"
requires-python = ">=3.14"
dependencies = [
  "numpy",
  "pandas",
  "seaborn",
  "matplotlib",
  "multiscat",
  "numpy>=2.0.0,<3.0.0",
    "scipy>=1.14.0,<2.0.0",
    "slate_core @ git+https://github.com/Matt-Ord/slate.git@e9669d0",
    "slate_quantum @ git+https://github.com/Matt-Ord/slate_quantum.git@45fb33b22f86840650680d4fac385369349cd0c5",
]

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "refactor",
]

[tool.uv.sources]
multiscat = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.15.6",
]
