#!/bin/bash

# A bash script to compare the output of compiling and 
#running the multiscat.f90 code with a reference

#Before running change permissions (look up chmod)
#Probably need: chmod u+x FMultiscatCaT
#Also eliminate Windows line returns (Windows why?!?!)
#using: sed -i -e 's/\r$//' FMultiscatCaT


# Declare an array of string with type
declare -a Directories=("Test1" "Test2")

for dir in ${Directories[@]}
do
	cd $dir
	# clears old compiled files and outputs
	rm -rf ./*.o
	rm -rf ./multiscat
	rm -rf ./*.f
	rm -rf ./*.f90
	rm -rf ./Makefile
	rm -rf ./*.6
	rm -rf ./*.inc

	#brings in the necessary files
	cp ../multiscat.f90 ./multiscat.f90 
	cp ../potsub.f90 ./potsub.f90 
	cp ../scatsub.f ./scatsub.f 
	cp ../diagsub.f ./diagsub.f
	cp ../pot10001.in ./pot10001.in
	cp ../FourierLabels.in ./FourierLabels.in 
	cp ../Makefile ./Makefile
	cp ../multiscat.inc ./multiscat.inc

	#Fixes the Windows carridge returns to allow files to be compared across operating systems
	sed -i -e 's/\r$//' Result.out


	printf '\n\nCleared directory for %s, rebuilding...\n\n' $dir
	#re-compiles new files
	make

	#executes
	printf 'Executing Multiscat ...\n\n'
	multiscat Multiscat.conf

	#tests
	f1='./diffrac10001.out'
	f2='./Result.out'

	if cmp -s "$f1" "$f2"
	then
	    printf '##### Test passed, .out file behaved as expected #####\n'
	else
	    printf '##### WARNING: Test %s failed  #####\n' $dir
	fi

	#Remove compiled files
	rm -rf ./*.o
	rm -rf ./multiscat
	rm -rf ./*.6
	# Return to parent directory
	cd ./..
done