program pot2lobatto
  implicit double precision (a-h,o-z)
  include 'multiscat.inc'

  character*256 inputfile, outputfile, arg
  integer nfc, nzin, m
  integer ios
  complex*16 vfcfixed(NZFIXED_MAX,NVFCFIXED_MAX)
  complex*16 vfc(mmax,nfcx)
  dimension w(mmax), z(mmax), t(mmax,mmax)

  call getarg(1, inputfile)
  call getarg(2, outputfile)
  call getarg(3, arg)
  if (trim(arg).eq.'') then
    call print_usage_and_stop()
  end if
  read(arg, *, iostat=ios) nfc
  if (ios.ne.0) call print_usage_and_stop()

  call getarg(4, arg)
  if (trim(arg).eq.'') then
    call print_usage_and_stop()
  end if
  read(arg, *, iostat=ios) nzin
  if (ios.ne.0) call print_usage_and_stop()

  call getarg(5, arg)
  if (trim(arg).eq.'') then
    call print_usage_and_stop()
  end if
  read(arg, *, iostat=ios) zmin
  if (ios.ne.0) call print_usage_and_stop()

  call getarg(6, arg)
  if (trim(arg).eq.'') then
    call print_usage_and_stop()
  end if
  read(arg, *, iostat=ios) zmax
  if (ios.ne.0) call print_usage_and_stop()

  if (nfc.lt.1 .or. nfc.gt.nfcx) then
    stop 'ERROR: nfc must satisfy 1 <= nfc <= nfcx.'
  end if
  if (nzin.lt.2 .or. nzin.gt.NZFIXED_MAX) then
    stop 'ERROR: nzin must satisfy 2 <= nzin <= NZFIXED_MAX.'
  end if
  if (zmax.le.zmin) then
    stop 'ERROR: zmax must be greater than zmin.'
  end if

  call read_fixed_potential(inputfile, nfc, nzin, vfcfixed)

  m = mmax
  call tshape(zmin, zmax, m, w, z, t)
  call potent(zmin, zmax, nzin, vfcfixed, nfc, vfc, m, z)

  call write_fixed_potential(outputfile, nfc, m, vfc)
end program pot2lobatto


subroutine print_usage_and_stop()
  implicit double precision (a-h,o-z)
  print *, 'Usage:'
  print *, '  pot2lobatto <input_pot> <output_pot> <nfc> <nzin> <zmin> <zmax>'
  stop 'ERROR: invalid arguments.'
end subroutine print_usage_and_stop


subroutine read_fixed_potential(inputfile, nfc, nzin, vfcfixed)
  implicit double precision (a-h,o-z)
  include 'multiscat.inc'

  integer nfc, nzin
  integer i, j
  character*(*) inputfile
  character*256 header_line
  complex*16 vfcfixed(NZFIXED_MAX,NVFCFIXED_MAX)

  vfcfixed = (0.0d0, 0.0d0)
  open(20, file=inputfile, status='old', action='read')

  do i=1,5
    read(20, '(A)') header_line
  end do

  do i=1,nfc
    do j=1,nzin
      read(20, *) vfcfixed(j,i)
    end do
  end do

  close(20)
end subroutine read_fixed_potential


subroutine write_fixed_potential(outputfile, nfc, nzout, vfc)
  implicit double precision (a-h,o-z)
  include 'multiscat.inc'

  integer nfc, nzout
  integer i, j
  character*(*) outputfile
  complex*16 vfc(mmax,nfcx)

  open(21, file=outputfile, status='replace', action='write')
  write(21, '(A)') 'Generated by pot2lobatto'
  write(21, '(A)') 'Potential in Lobatto z basis for multiscat input'
  write(21, '(A)') 'Format: (real, imag)'
  write(21, '(A)') 'Ordering: Fourier component then z-slice'
  write(21, '(A)') 'Do not edit by hand'

  do i=1,nfc
    do j=1,nzout
      write(21, '("(",SP,ES13.6,", ",SP,ES13.6,")")') dble(vfc(j,i)), dimag(vfc(j,i))
    end do
  end do

  close(21)
end subroutine write_fixed_potential